### ISSUE TITLE
Pojašnjenje animacije iz README.md

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp/2020_ParGenAlg#2]
Izgleda na prvi pogled da obilazak nije baš ispravan, možda je do brzine animacije. Da li možete malo da pojasnite šta se dešava?

**Comment by Robotmurlock** [comment]
Postavili smo novu animaciju snimljenu kao mp4 kojoj se može pristupiti indirektno preko linka (klikom na sliku), pošto github ne podržava mp4 format. Trebalo bi da sad bude preglednije u odnosu na prethodnu (gif) verziju. Takođe, prethodna animacija je imala početku tačku Beograd (što je verovatno još jedan razlog zašto je animacija bila čudna). Nova animacija počinje iz Subotice.
